### ISSUE TITLE
column tokens.refreshToken does not exist

### ISSUE THREAD

**Issue by scottillogical** [LandonPatmore/yahoo-fantasy-bot#71]
Noticed i wasn't getting any notifications and saw this error in the logs
```
20-09-25T18:36:14.770869+00:00 app[bot.1]: at com.landonpatmore.yahoofantasybot.bot.MainKt.main(Main.kt)
2020-09-25T18:36:14.771019+00:00 app[bot.1]: Caused by: org.postgresql.util.PSQLException: ERROR: column tokens.refreshToken does not exist
2020-09-25T18:36:14.771020+00:00 app[bot.1]: Hint: Perhaps you meant to reference the column "tokens.refreshtoken".
2020-09-25T18:36:14.771054+00:00 app[bot.1]: Position: 8
2020-09-25T18:36:14.771117+00:00 app[bot.1]: at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
2020-09-25T18:36:14.771182+00:00 app[bot.1]: at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)

```
I'm running this sha bcc1e52ad9a953797b0c0ab0875ab661e4313d4d.  I updated my bot by doing a git pull from master and redeploying to heroku, is that what caused my issue vs deleting the app?

Is the only fix to delete the app and redeploy? I tried adding the column by hand but actually had an issue doing that, heh

```020-09-25T18:36:14.770869+00:00 app[bot.1]: at com.landonpatmore.yahoofantasybot.bot.MainKt.main(Main.kt)
2020-09-25T18:36:14.771019+00:00 app[bot.1]: Caused by: org.postgresql.util.PSQLException: ERROR: column tokens.refreshToken does not exist
2020-09-25T18:36:14.771020+00:00 app[bot.1]: Hint: Perhaps you meant to reference the column "tokens.refreshtoken".
2020-09-25T18:36:14.771054+00:00 app[bot.1]: Position: 8```

Thanks!!

**Comment by LandonPatmore** [comment]
It looks like you’re using your own fork.  Yah I changed the DB tables around.  Your bot had the old tables and when the new table checker checks to see if the table exists, it doesn’t check to see if the columns are there.  It only looks to see if the named table exists.

Since you deleted the old bot and redeployed it, the old Postgres DB was feted and a new one was created with all the tables with the correct columns.

**Comment by LandonPatmore** [comment]
However, now you have the latest tables and such and those won’t be changing unless something drastic happens, you can use your fork now and continually deploy like you have without having to delete the bot.
